# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "wuhulamb"
title_separator          : "-"
subtitle                 : "记录·分享·表达" # site tagline that appears below site title in masthead
name                     : "wuhulamb"
description              : "a blog site"
url                      : "https://wuhulamb.github.io"
baseurl                  : # "."
repository               : "wuhulamb/wuhulamb.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # "/media/favicon/android-chrome-512x512.png"
logo                     : "/media/favicon/favicon.ico"
masthead_title           : # "test" overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 100
comments:
  provider               : "giscus" # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  giscus:
    repo_id              : "R_kgDOMdvvVQ" # Shown during giscus setup at https://giscus.app
    category_name        : "Announcements" # Full text name of the category
    category_id          : "DIC_kwDOMdvvVc4ChU4o" # Shown during giscus setup at https://giscus.app
    discussion_term      : "pathname" # "pathname" (default), "url", "title", "og:title"
    strict               : "1" # '1' for enabled (default), '0' for disabled
    reactions_enabled    : "1" # '1' for enabled (default), '0' for disabled
    emit-metadata        : "0" # '1' for enabled, '0' for disabled (default)
    input-position       : "bottom" # "bottom" (default)
    theme                : "light" # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
    lang                 : "en" # en (default)
    loading              : "lazy"  # or delete this + comments-providers/giscus.html loading
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)
search                   : true
search_full_content      : true
search_provider          : lunr # lunr (default), algolia, google
lunr:
  search_within_pages    : true # true, false (default)
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)

# /media/favicon/android-chrome-512x512.png
# /media/image/2024/04/black-spiderman.jpg
# Site Author
author:
  name             : "wuhulamb"
  avatar           : "media/favicon/android-chrome-192x192.jpg"
  bio              : "Viva La Vida!"
  location         : "Wuhu, Anhui"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:wuhulamb@163.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wuhulamb"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wuhulamb"


# Reading Files
include:
  - _pages
exclude:
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - config
  - Gemfile
  - README

keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "<!--more-->"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /blog/:year/:month/:day/:title/
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num/
timezone: Asia/Shanghai


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

collections:
  excerpts:
    output: true
    permalink: /read/:year/:month/:day/:title/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: false
      related: true
      show_date: true
      toc: true
      toc_sticky: true
      toc_label: "Table of Contents"
      tag_show: true
  # _excerpts
  - scope:
      path: ""
      type: excerpts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: false
      related: true
      show_date: true
      toc: false
      my-paragraph: true
      tag_show: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # nav
  - scope:
      path: ""
    values:
      sidebar:
        nav: "web"
  # header overlay_image
  - scope:
      path: ""
    values:
      header:
        overlay_image:           "/assets/hero-img/posts/default-sunrise-fox.jpg"
        show_overlay_excerpt:    false
      mathjax:                   false
      my-paragraph:              false
